name: onvif
version: 3.0.1
homepage: https://github.com/faithoflifedev/easy_onvif
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.
repository: https://github.com/faithoflifedev/easy_onvif
environment:
  sdk: ">=3.2.0 <4.0.0"

publish_to: "none"

dependencies:
  args: ^2.4.2
  easy_onvif:
    path: ../
  universal_io: ^2.2.2
