name: easy_onvif
version: 3.0.1+2
homepage: https://github.com/faithoflifedev/easy_onvif
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.
repository: https://github.com/faithoflifedev/easy_onvif
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ansi_escapes: ^1.1.0
  ansicolor: ^2.0.3
  archive: ^3.6.1
  args: ^2.5.0
  cli_spin: ^1.0.1
  convert: ^3.1.1
  crypto: ^3.0.5
  dio: ^5.7.0
  ffi: ^2.1.3
  html_unescape: ^2.0.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sprintf: ^7.0.0
  universal_io: ^2.2.2
  uuid: ^4.5.1
  xml: ^6.5.0
  xml2json: ^6.2.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^5.0.0
  publish_tools: ^1.0.0+5
  test: ^1.25.8

executables:
  onvif:
